var FaceTecStrings = {
  "FaceTec_action_ok": "OK",
  "FaceTec_action_im_ready": "İDENTİFİKASİYA ÜÇÜN HAZIRAM",
  "FaceTec_action_try_again": "YENİDƏN CƏHD EDİN",
  "FaceTec_action_continue": "DAVAM ET",
  "FaceTec_action_take_photo": "ŞƏKİL ÇƏK",
  "FaceTec_action_accept_photo": "QƏBUL ET",
  "FaceTec_action_retake_photo": "YENİDƏN ÇƏK",
  "FaceTec_action_confirm": "MƏLUMATI TƏSDFİQ ET",

  "FaceTec_accessibility_cancel_button": "Ləğv Et",
  "FaceTec_accessibility_tap_guidance": "Üzünüzlə uyğunlaşma rəhbərliyi üçün ekranı iki dəfə vurun",
  "FaceTec_accessibility_key_down_guidance": "Üzünüzlə uyğunlaşma rəhbərliyi üçün Enter və ya Spacebar düyməsini basın",

  "FaceTec_accessibility_feedback_move_phone_away": "Kamera çox yaxın",
  "FaceTec_accessibility_feedback_move_phone_closer": "Kamera çox uzaq",
  "FaceTec_accessibility_feedback_face_too_far_left": "Üz çox sola",
  "FaceTec_accessibility_feedback_face_too_far_right": "Üz çox sağa",
  "FaceTec_accessibility_feedback_face_too_low": "Üz çox aşağı",
  "FaceTec_accessibility_feedback_face_too_high": "Üz çox yuxarı",
  "FaceTec_accessibility_feedback_face_rotated_too_far_left": "Üz çox sola döndürülmüşdür",
  "FaceTec_accessibility_feedback_face_rotated_too_far_right": "Üz çox sağa döndürülmüşdür",
  "FaceTec_accessibility_feedback_face_looking_too_far_left": "Üz çox sola baxır",
  "FaceTec_accessibility_feedback_face_looking_too_far_right": "Üz çox sağa baxır",
  "FaceTec_accessibility_feedback_face_not_in_camera": "Üz kamerada deyil və ya çox uzaqda",
  "FaceTec_accessibility_feedback_hold_phone_to_eye_level": "Cihazı göz səviyyəsinə tutun",
  "FaceTec_accessibility_feedback_move_away_web": "Kamera çox yaxın",
  "FaceTec_accessibility_feedback_move_closer_web": "Kamera çox uzaq",
  "FaceTec_accessibility_feedback_hold_to_eye_level_web": "Kameranı göz səviyyəsinə gətirin",

  "FaceTec_presession_frame_your_face": "Üzünüzü ovalda çərçivələyin",
  "FaceTec_presession_look_straight_ahead": "Düz baxın",
  "FaceTec_presession_hold_steady3": "Sabit saxlayın: 3",
  "FaceTec_presession_hold_steady2": "Sabit saxlayın: 2",
  "FaceTec_presession_hold_steady1": "Sabit saxlayın: 1",
  "FaceTec_presession_eyes_straight_ahead": "Düz baxın",
  "FaceTec_presession_remove_dark_glasses": "Qara gözlüyü yığın",
  "FaceTec_presession_neutral_expression": "Neytral ifadə, gülümsəməyin yoxdur",
  "FaceTec_presession_conditions_too_bright": "Şəraiti çox parlaq",
  "FaceTec_presession_brighten_your_environment": "Mühitinizi daha çox parlaqlaşdırın",

  "FaceTec_feedback_center_face": "Üzü mərkəzləşdirin",
  "FaceTec_feedback_face_not_found": "Üzü çərçivələyin",
  "FaceTec_feedback_move_phone_away": "Uzaqlaşın",
  "FaceTec_feedback_move_away_web": "Uzaqlaşın",
  "FaceTec_feedback_move_phone_closer": "Yaxınlaşın",
  "FaceTec_feedback_move_web_closer": "Üzün Yaxınlaşdırın və Oval Doldurun",
  "FaceTec_feedback_move_web_even_closer": "Daha da yaxınlaşın",
  "FaceTec_feedback_move_phone_to_eye_level": "Cihazı göz səviyyəsinə gətirin",
  "FaceTec_feedback_move_to_eye_level_web": "Kamera üzünə düz baxın",
  "FaceTec_feedback_face_not_looking_straight_ahead": "Düz baxın",
  "FaceTec_feedback_face_not_upright": "Başını düz saxlayın",
  "FaceTec_feedback_face_not_upright_mobile": "Keep Head Straight",
  "FaceTec_feedback_hold_steady": "Hold Steady",
  "FaceTec_feedback_use_even_lighting": "Light Face More Evenly",

  "FaceTec_instructions_header_ready_desktop": "İdentifikasiyaya hazır olun",
  "FaceTec_instructions_header_ready_1_mobile": "Hazır olun",
  "FaceTec_instructions_header_ready_2_mobile": "Video Selfie",
  "FaceTec_instructions_message_ready_desktop": "Üzünüzü Ovallıqda Çərçivələyin, MƏN HAZIRAM düyməsini basın və Yaxınlaşın",
  "FaceTec_instructions_message_ready_1_mobile": "Üzünüzü Ovallıqda Çərçivələyin,",
  "FaceTec_instructions_message_ready_2_mobile": "MƏN HAZIRAM düyməsini basın",

  "FaceTec_retry_header": "Bunu Bir Daha Cəhd Edək",
  "FaceTec_retry_subheader_message": "Bizə daha aydın bir Video Selfie lazımdır",
  "FaceTec_retry_your_image_label": "Öz Şəkiliniz",
  "FaceTec_retry_ideal_image_label": "İdeal Poz",
  "FaceTec_retry_instruction_message_1": "Xahiş edirəm İdeal Poz və Aydınlatma istifadə edin",
  "FaceTec_retry_instruction_message_2": "Neytr İfadə, Gülümsəməyin Yoxdur",
  "FaceTec_retry_instruction_message_3": "Çox Bulanıq, Təmiz Kamera",

  "FaceTec_camera_feed_issue_header": "Kamera Lentinin Təhlükəsizliyi Problemi",
  "FaceTec_camera_feed_issue_header_mobile": "Kamera Yayınının<br/>Məsələsi",
  "FaceTec_camera_feed_issue_subheader_message_mobile": "Bu Tətbiq şübhəli veb kameraları qoruyur.<br/><a href='https://livenesscheckhelp.com/' target='_blank' style='text-decoration:underline; font:inherit; pointer-events:all;'>Daha Ətraflı Məlumat</a>.",
  "FaceTec_camera_feed_issue_subheader_message": "Bu sistem aşağıdakı səbəbdən doğrulanmır:",
  "FaceTec_camera_feed_issue_table_header_1": "Mümkün Məsələ",
  "FaceTec_camera_feed_issue_table_header_2": "Təkmilləşdir",
  "FaceTec_camera_feed_issue_table_row_1_cell_1_firefox_permissions_error": "Firefox-da Kamera icazələri yadda saxlanmır.",
  "FaceTec_camera_feed_issue_table_row_1_cell_2_firefox_permissions_error": "İcazələri Xatırlayın yoxlayın.",
  "FaceTec_camera_feed_issue_table_row_1_cell_1": "Kamera artıq başqa Tətbiq tərəfindən istifadə olunur.",
  "FaceTec_camera_feed_issue_table_row_1_cell_2": "Başqa Tətbiqi bağlayın.",
  "FaceTec_camera_feed_issue_table_row_2_cell_1": "Üçüncü Tərəf Tətbiqi videoya müdaxilə edir.",
  "FaceTec_camera_feed_issue_table_row_2_cell_2": "Başqa Tətbiqi bağlayın/Silin.",
  "FaceTec_camera_feed_issue_table_row_3_cell_1": "Təhlükəsiz olmağa qabiliyyəti olmayan Hardware.",
  "FaceTec_camera_feed_issue_table_row_3_cell_2": "Başqa Qurğu İstifadə Edin.",
  "FaceTec_camera_feed_issue_subtable_message": "Bu Tətbiq şübhəli veb kameraları qoruyur. <a href='https://livenesscheckhelp.com/' target='_blank' style='text-decoration:underline; font:inherit; pointer-events:all;'>Daha Ətraflı Məlumat</a>.",
  "FaceTec_camera_feed_issue_action": "HƏR HALDA YENİDƏN CƏHD EDİN",
  "FaceTec_camera_feed_issue_action_firefox_permissions_error": "OK",

  "FaceTec_camera_permission_header": "Kameranı İcazələndir",
  "FaceTec_camera_permission_message": "Kamera icazələri söndürülmüşdür.<br/>Xahiş edirəm əməliyyat sistem və brauzer parametrlərinizi yoxlayın.",

  "FaceTec_enter_fullscreen_header": "Tam Ekran Selfie Rejimi",
  "FaceTec_enter_fullscreen_message": "Biz başlamazdan əvvəl, lütfən aşağıdakı düyməyə basaraq tam ekran rejimini açın.",
  "FaceTec_enter_fullscreen_action": "TAM EKRANI AÇIN",

  "FaceTec_initializing_camera": "Kamera Lentinin Təhlükəsizliyi Prosəsi",

  "FaceTec_idscan_type_selection_header": "ID Sənədinizin Skan Edilməsi üçün Hazırla",
  "FaceTec_idscan_capture_id_front_instruction_message": "ID-nin Önünü Göstərin",
  "FaceTec_idscan_capture_id_back_instruction_message": "ID-nin Arxasını Göstərin",
  "FaceTec_idscan_review_id_front_instruction_message": "Şəkilin Aydın və Oxunaqlı Olduğunu Təsdiqləyin",
  "FaceTec_idscan_review_id_back_instruction_message": "Şəkilin Aydın və Oxunaqlı Olduğunu Təsdiqləyin",
  "FaceTec_idscan_additional_review_message": "Əlavə İncelemə<br/>Tələb Olunur",
  "FaceTec_idscan_ocr_confirmation_main_header": "İnceleyin və Təsdiqləyin",
  "FaceTec_idscan_ocr_confirmation_scroll_message": "Aşağıya Kaydırın",

  "FaceTec_result_success_message": "Uğur!",
  "FaceTec_result_facescan_upload_message": "Yüklənir<br/>Şifrələnmiş<br/>3D FaceScan",
  "FaceTec_result_idscan_upload_message": "Yüklənir<br/>Şifrələnmiş<br/>ID Sənədi",
  "FaceTec_result_idscan_unsuccess_message": "ID Şəkli<br/>İstifadəçinin Üzünə Uyğun Gəlmir",
  "FaceTec_result_idscan_success_front_side_message": "ID Skan Tamamlandı",
  "FaceTec_result_idscan_success_front_side_back_next_message": "ID-nin Əvvəli<br/>Tərəfinə Skan Edildi",
  "FaceTec_result_idscan_success_back_side_message": "ID Skan Tamamlandı",
  "FaceTec_result_idscan_success_passport_message": "Passport Skan Tamamlandı",
  "FaceTec_result_idscan_success_user_confirmation_message": "Şəkil ID Skanı<br/>Tamamlandı",
  "FaceTec_result_idscan_success_additional_review_message": "ID Şəklinin Çəkilməsi Tamamlandı",
  "FaceTec_result_idscan_retry_face_did_not_match_message": "Üz Uyğun Gəlmir<br/>Kifayət Qədər Yüksək Deyil",
  "FaceTec_result_idscan_retry_id_not_fully_visible_message": "ID Sənədi<br/>Tamamilə Görmək Mümkün Deyil",
  "FaceTec_result_idscan_retry_ocr_results_not_good_enough_message": "ID Mətni Oxunaq Deyil",
  "FaceTec_result_idscan_retry_id_type_not_suppported_message": "ID Növü Dəstəklənmir<br/>Xahiş edirəm başqa bir ID istifadə edin",
  "FaceTec_result_idscan_retry_barcode_not_read_message": "Barkod Oxunmadı<br/>Zəhmət olmasa Yenidən Cəhd Edin",
};

module.exports = FaceTecStrings;